### PR TITLE
Integrity check to data length as length is read from a client.

### LINKED ISSUE #6: Memory leak when reading bytes.
Any ideas on this?

I'm using Microsoft Owin static files server, Kentor cookie saver and AesDataProtectorProvider:
```
Owin.Security.AesDataProtectorProvider (1.1.1)
Kentor.OwinCookieSaver (1.1.1)
Microsoft.Owin.StaticFiles (3.1)
```

My Owin registration (in fsharp, but csharp would be very similar):

```fsharp
    member __.Configuration(ap:Owin.IAppBuilder) =
        ap.UseAesDataProtectorProvider("my-key") |> ignore
        ap.UseKentorOwinCookieSaver() |> ignore
        ap.UseFileServer(fileServerOptions) |> ignore
```

For some reasons sometimes the server hangs (with Chrome) and starts to leak a huge amount of memory. When debugged, it seems to raise the following exception, the callstack won't have my code at all:

{"Non-negative number required.\r\nParameter name: count"}	System.ArgumentOutOfRangeException
	mscorlib.dll!System.IO.BinaryReader.ReadBytes(int count)	Unknown
 	Owin.Security.AesDataProtectorProvider.dll!Owin.Security.AesDataProtectorProvider.AesDataProtector.Unprotect(byte[] protectedData)	Unknown
 	Microsoft.Owin.Security.dll!Microsoft.Owin.Security.DataHandler.SecureDataFormat<Microsoft.Owin.Security.AuthenticationTicket>.Unprotect(string protectedText)	Unknown
 	Microsoft.Owin.Security.Cookies.dll
--cut--
 	mscorlib.dll!System.Threading._IOCompletionCallback.PerformIOCompletionCallback(uint errorCode, uint numBytes, System.Threading.NativeOverlapped* pOVERLAP)	Unknown

### PR DESCRIPTION
**Pull request by Thorium**
I didn't manage to verify this. But this check shouldn't hurt anything, right?
"If couldn't read, then just return nothing and go-on with your life."

### CODE REVIEW

**Comment by i4004** [comment]
Yeah, i think it will not hurt anything, but anyway we should reproduce the problem before making any changes.

**Comment by Thorium** [comment]
This didn't help. I think the problem might be overflow of Int32 and that what caused it to be negative.

But why is the length so large, is probably just a side-effect of the real problem, which is the memory leak. 

After this the same code line fails sometimes for "Padding is invalid and cannot be removed", so there was no help in this case. I'll try to figure out more.

**Comment by i4004** [comment]
Agree, because that ReadInt32 function can only return unsigned ints and throw exceptions.

**Comment by Thorium** [comment]
If my protectedData is byte[304], is it normal that my len is 2000345262 ?

**Pull request merged**
